# Generated by Django 5.1.2 on 2024-10-17 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название фигуры')),
                ('shape', models.CharField(max_length=50, verbose_name='Форма фигуры')),
                ('text_color', models.CharField(max_length=20, verbose_name='Цвет текста')),
                ('back_color', models.CharField(max_length=20, verbose_name='Цвет фона')),
                ('border_color', models.CharField(max_length=20, verbose_name='Цвет границы')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Формы',
            },
        ),
        migrations.CreateModel(
            name='LineEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1, verbose_name='Название типа конца линии')),
            ],
            options={
                'verbose_name': 'Тип конца линии',
                'verbose_name_plural': 'Типы концов линии',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название типа элемента')),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_types', to='tech_items.figure', verbose_name='Фигура')),
            ],
            options={
                'verbose_name': 'Тип элемента',
                'verbose_name_plural': 'Типы элементов',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название элемента')),
                ('description', models.TextField(verbose_name='Описание элемента')),
                ('icon', models.CharField(max_length=6, verbose_name='Иконка')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='tech_items.itemtype', verbose_name='Тип элемента')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название типа связи')),
                ('out_type_mult', models.BooleanField(verbose_name='Группировка источников')),
                ('in_type_mult', models.BooleanField(verbose_name='Группировка приемников')),
                ('line_solid', models.BooleanField(verbose_name='Непрерывная')),
                ('line_color', models.CharField(max_length=20, verbose_name='Цвет линии')),
                ('in_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relation_in_types', to='tech_items.itemtype', verbose_name='Тип приемника')),
                ('line_in_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relation_type_in_set', to='tech_items.lineend', verbose_name='Конец приемника')),
                ('line_out_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relation_type_out_set', to='tech_items.lineend', verbose_name='Конец источника')),
                ('out_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relation_out_types', to='tech_items.itemtype', verbose_name='Тип источника')),
            ],
            options={
                'verbose_name': 'Тип взаимосвязи',
                'verbose_name_plural': 'Типы взаимосвязей',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_group_id', models.IntegerField(verbose_name='ID группы источника')),
                ('out_group_sort', models.IntegerField(verbose_name='Индекс в группе источника')),
                ('in_group_id', models.IntegerField(verbose_name='ID группы приемника')),
                ('in_group_sort', models.IntegerField(verbose_name='Индекс в группе приемника')),
                ('in_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relations_in', to='tech_items.item', verbose_name='Источник')),
                ('out_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relations_out', to='tech_items.item', verbose_name='Источник')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relations', to='tech_items.relationtype', verbose_name='Тип взаимосвязи')),
            ],
        ),
    ]
