# Generated by Django 5.1.2 on 2024-10-19 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationtype',
            name='icon',
            field=models.CharField(blank=True, max_length=10, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='item',
            name='icon',
            field=models.CharField(blank=True, max_length=10, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='in_group_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID группы приемника'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='in_group_sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='Индекс в группе приемника'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='in_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relations_in', to='tech_items.item', verbose_name='Приемник'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='out_group_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID группы источника'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='out_group_sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='Индекс в группе источника'),
        ),
    ]
